# Finding the optimal policy

In [0]:
import numpy as np

### Define the graph as an MDP with states, actions & transitions

![graph](https://drive.google.com/uc?id=11XU7Qm4jlOVhCf5q5126jmS6dKFcXBtP)

Definition of states and their respective types: 
 - `0`: absorbing state
 - `1`: regular state

In [0]:
states = { 0: 1,
            1: 1,
            2: 1,
            3: 1,
            4: 1,
            5: 1,
            6: 1,
            7: 1,
            8: 1,
            9: 0
}



Mapping of states to the list of actions that can be taken. Actions are considered in a clockwise order given a state in the graph. 

In [0]:
actions = { 0: (0,1,2),
            1: (0,1),
            2: (0,1),
            3: (0,1),
            4: (0,1),
            5: (0,1, 2, 3),
            6: (0,1),
            7: (0,1),
            8: (0,1),
            9: (0,)
}

Mapping of a state and an action to the resulting state and reward: `(s1, a) -> (s2, r)` where `s1` is the current state and `a` is the action taken, resulting in state `s2` and yielding reward `r`.

In [0]:
transitions = {
    # state 0
    (0,0) : (1,-5),
    (0,1) : (2, -2),
    (0,2) : (3, 1),
    # state 1
    (1,0) : (4, -2),
    (1,1) : (2, 1),
    # state 2
    (2,0) : (5, 3),
    (2,1) : (3, 2),
    # state 3
    (3,0) : (5, -1),
    (3,1) : (6, -5),
    # state 4
    (4,0) : (7, -2),
    (4,1) : (5, 5),
    # state 5
    (5,0) : (7, -2),
    (5,1):  (8 , -4),
    (5, 2): (9, -7),
    (5, 3): (6, -2),
    # state 6
    (6,0): (5, -3),
    (6,1): (9, 1),
    # state 7
    (7,0) : (8, -4),
    (7,1): (5, -2),
    # state 8
    (8,0) :(9, 10),
    (8,1): (5, -4),
    # state 9 (absorbing state)
    (9,0) :(9, 0)
}



`MDP` defines a Markov decision process, based on the graph above.

In [0]:
MDP = {
    "states" : states,
    "actions": actions,
    "transitions" : transitions
}


Some policies..  

A policy maps a state `s` to a list of probabilities `p`, in which the `i`*th* probability `p_i` is the probability that the `i`*th* action from `actions[s]` is taken in state `s`.

In [0]:
policy1 = {
    0: [0,1,0],
    1: [0,1],
    2: [0,1],
    3: [1, 0],
    4: [1, 0],
    5: [0, 1, 0, 0],
    6: [0, 1],
    7: [1, 0],
    8: [1, 0]
}

policy2 = {
    0: [0.3,0.5,0.2],
    1: [0, 1],
    2: [0, 1],
    3: [1, 0],
    4: [1, 0],
    5: [0, 1, 0, 0],
    6: [0, 1],
    7: [1, 0],
    8: [1, 0]
}


policy3 = {
    0: [0.4,0.2,0.4],
    1: [0.7,0.3],
    2: [0.4,0.6],
    3: [0.7,0.3],
    4: [0.2,0.8],
    5: [0.25,0.25,0.25,0.25],
    6: [1, 0],
    7: [0.5,0.5],
    8: [0.6,0.4]
}


### Determine the optimal value function.

$$
v^{\star}(s) = \max_{a}q^{\star}(s,a)
\\
\\
$$

$$
q^{\star}(s,a) = \sum_{s'}p(s'|s,a)\left[r(s,a,s') + \gamma v^{\star}(s') \right]
$$

with
$$
\gamma = 1 
$$
and
$$
p(s'|s,a) = 1
$$
it results in 
$$
q^{\star}(s,a) = r(s,a,s') + \gamma v^{\star}(s')
$$


In [0]:
v_star = np.zeros(10)
number_states = 10

for iteration in np.arange(15):
    q_star = np.zeros((10, 4))
    for s in np.arange(number_states):
        for a in MDP['actions'][s]:
            r= MDP['transitions'][(s, a)][1]
            nextState = MDP['transitions'][(s, a)][0]
            q_star[s, a] =  r + v_star[nextState]
    v_star = np.max(q_star, axis=1)
    print(v_star)


for i in range(number_states):
  print(f"State {i}: {v_star[i]}")
print("============== Q table ==============" )
print("   a_0 a_1 a_2 a_3")
print(q_star)

[ 1.  1.  3.  0.  5. -2.  1.  0. 10.  0.]
[ 1.  4.  2.  0.  3.  6.  1.  6. 10.  0.]
[ 1.  3.  9.  5. 11.  6.  3.  6. 10.  0.]
[ 7. 10.  9.  5. 11.  6.  3.  6. 10.  0.]
[ 7. 10.  9.  5. 11.  6.  3.  6. 10.  0.]
[ 7. 10.  9.  5. 11.  6.  3.  6. 10.  0.]
[ 7. 10.  9.  5. 11.  6.  3.  6. 10.  0.]
[ 7. 10.  9.  5. 11.  6.  3.  6. 10.  0.]
[ 7. 10.  9.  5. 11.  6.  3.  6. 10.  0.]
[ 7. 10.  9.  5. 11.  6.  3.  6. 10.  0.]
[ 7. 10.  9.  5. 11.  6.  3.  6. 10.  0.]
[ 7. 10.  9.  5. 11.  6.  3.  6. 10.  0.]
[ 7. 10.  9.  5. 11.  6.  3.  6. 10.  0.]
[ 7. 10.  9.  5. 11.  6.  3.  6. 10.  0.]
[ 7. 10.  9.  5. 11.  6.  3.  6. 10.  0.]
State 0: 7.0
State 1: 10.0
State 2: 9.0
State 3: 5.0
State 4: 11.0
State 5: 6.0
State 6: 3.0
State 7: 6.0
State 8: 10.0
State 9: 0.0
============== Q table ==============
   a_0 a_1 a_2 a_3
[[ 5.  7.  6.  0.]
 [ 9. 10.  0.  0.]
 [ 9.  7.  0.  0.]
 [ 5. -2.  0.  0.]
 [ 4. 11.  0.  0.]
 [ 4.  6. -7.  1.]
 [ 3.  1.  0.  0.]
 [ 6.  4.  0.  0.]
 [10.  2.  0.  0.]
 [ 0.  0.

![optValue](https://drive.google.com/uc?id=1F6lv_-faTNFPuVpn6a3ijtGm3SnE_Deh)